# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170418_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='blood',
            field=models.CharField(default=b'', max_length=8),
        ),
        migrations.AddField(
            model_name='users',
            name='blood_type',
            field=models.CharField(default=b'', max_length=8),
        ),
        migrations.AddField(
            model_name='users',
            name='latitude',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='longitude',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(default=b'9508233223', max_length=20),
        ),
    ]
