# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170419_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=120, unique=True)),
                ('dis_name', models.CharField(max_length=120)),
                ('dis_severity', models.CharField(max_length=120)),
                ('dis_probname', models.CharField(max_length=120)),
                ('dis_hint', models.CharField(max_length=120)),
                ('dis_time', models.CharField(max_length=120)),
            ],
        ),
    ]
